<?php 

/**
 * Implements hook_menu().
 */
function redactor_filemanager_menu() {
  $items['redactor/filemanager/%wysiwyg_profile/upload'] = array(
    'title' => 'Redactor file upload',
    'description' => 'Ajax callback to upload files from Redactor editor',
    'page arguments' => array(2),
    'page callback' => 'redactor_filemanager_upload',
    'access callback' => 'redactor_filemanager_access_callback',
    'access arguments' => array(2, 'redactor upload files'),
    'type' => MENU_CALLBACK,
  );

  $items['redactor/filemanager/%wysiwyg_profile/files.json'] = array(
    'title' => 'Redactor file list',
    'description' => 'Ajax callback to list files from Redactor editor',
    'page arguments' => array(2),
    'page callback' => 'redactor_filemanager_list',
    'access callback' => 'redactor_filemanager_access_callback',
    'access arguments' => array(2, 'redactor list files'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function redactor_filemanager_access_callback($wysiwyg_profile, $permission) {
  $format = filter_format_load($wysiwyg_profile->format);
  return user_access($permission) && filter_access($format);
}

/**
 * return json file of public images
 */
function redactor_filemanager_list($wysiwyg_profile) {
  $files_urls = array();

  $config = redactor_get_plugin_config('filemanager', $wysiwyg_profile);

  $files = file_scan_directory(
    $config['upload_dir'], '/\.(' . join(drupal_explode_tags($config['extensions']), '|') . ')$/',
    array(
      'recurse' => false
    )
  );

  foreach($files as $file) {
    $url = parse_url(file_create_url($file->uri));
    $files_urls[] = array(
      'link'  => $url['path'],
      'size'  => format_size(filesize($file->uri)),
      'name'  => $file->name,
      'title' => $file->name
    );
  }

  return drupal_json_output($files_urls);
}


/**
 * Implements hook_permission().
 */
function redactor_filemanager_permission() {
  return array(
    'redactor upload files' => array(
      'title' => t('Upload files'),
      'description' => t('Allows the user to upload files with the Redactor editor'),
    ),
    'redactor list files' => array(
      'title' => t('List files'),
      'description' => t('Allows the user to list files with the Redactor editor'),
    ),
  );
}

/**
 * Callback to upload files
 */
function redactor_filemanager_upload($wysiwyg_profile) {
  $config = redactor_get_plugin_config('filemanager', $wysiwyg_profile);

  $file = file_unmanaged_copy($_FILES['file']['tmp_name'], $config['upload_dir'] . $_FILES['file']['name']);
  $filelink = file_create_url($file);

  $extension = pathinfo($file, PATHINFO_EXTENSION);

  drupal_json_output(array(
    'filename' => $_FILES['file']['name'],
    'filelink' => $filelink,
    'size' => format_size(filesize($file)),
    'mime' => file_get_mimetype($file),
    'ext' => $extension
  ));
}

/**
 * Implements hook_redactor_plugins.
 */
function redactor_filemanager_redactor_plugins($editor) {

  return array(
    'filemanager' => array(
      'name' => 'File manager',
      'files' => array(
        'js' => array(
          $editor['library path'] . '/plugins/filemanager.js' => array(),
        ),
      ),
      'config' => array(
        'extensions' => 'doc, xls, docx, pages, xlsx, zip, pdf',
        'upload_dir' => 'public://',
      ),
    ),
  );
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function redactor_filemanager_form_wysiwyg_profile_form_alter(&$form, &$form_state, $profile) {
  if($form_state['wysiwyg']['editor'] == 'redactor') {
    return;
  }

  $form['filemanager'] = array(
    '#type' => 'fieldset',
    '#title' => t('file manager settings'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#tree' => TRUE,
  );

  $profile = $form_state['wysiwyg_profile'];

  $profile = (array) $profile;

  if(empty($profile['settings']['filemanager'])) {
    $profile['settings']['filemanager'] = array();
  }

  $profile['settings']['filemanager'] += redactor_get_plugin_config('filemanager');
  $profile = (object) $profile;

  $form['filemanager']['extensions'] = array(
    '#type' => 'textfield',
    '#title' => 'Allowed file extensions',
    '#size' => 40,
    '#maxlength' => 250,
    '#default_value' => !empty($profile->settings['filemanager']['extensions']) ? $profile->settings['filemanager']['extensions'] : NULL,
    '#description' => 'comma seprated extensions',
  );

  $form['filemanager']['upload_dir'] = array(
    '#type' => 'textfield',
    '#title' => 'file directory',
    '#size' => 40,
    '#maxlength' => 250,
    '#default_value' => !empty($profile->settings['filemanager']['upload_dir']) ? $profile->settings['filemanager']['upload_dir'] : NULL,
    '#description' => 'directory where file will be uploaded'
  );
}

function redactor_filemanager_wysiwyg_editor_settings_alter(&$settings, $context) {
  if($context['editor']['name'] != 'redactor') {
    return;
  }

  if(!in_array('filemanager', $settings['plugins'])) {
    return;
  }

  $profile = $context['profile'];
  $settings['fileManagerJson'] = url('redactor/filemanager/'.$profile->format.'/files.json');
  $settings['fileUpload'] = url('redactor/filemanager/'.$profile->format.'/upload');
}
