<?php

/**
 * Implements hook_menu().
 */
function redactor_wysiwyg_menu() {
  $items = array();

  $items['redactor/imageupload'] = array(
    'title' => 'Redactor image upload',
    'description' => 'Ajax callback to upload image from Redactor editor',
    'page callback' => 'redactor_wysiwyg_imageupload',
    'access arguments' => array('upload images'),
    'type' => MENU_CALLBACK,
  );

  $items['redactor/fileupload'] = array(
    'title' => 'Redactor file upload',
    'description' => 'Ajax callback to upload files from Redactor editor',
    'page callback' => 'redactor_wysiwyg_fileupload',
    'access arguments' => array('upload files'),
    'type' => MENU_CALLBACK,
  );

  $items['redactor/linkfileupload'] = array(
    'title' => 'Redactor link file upload',
    'description' => 'Ajax callback to upload files from Redactor editor',
    'page callback' => 'redactor_wysiwyg_linkfileupload',
    'access arguments' => array('upload files'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function redactor_wysiwyg_permission() {
   return array(
    'upload images' => array(
      'title' => t('Upload images'),
      'description' => t('Allows the user to upload images with the Redactor editor'),
    ),
    'upload files' => array(
      'title' => t('Upload files'),
      'description' => t('Allows the user to upload files with the Redactor editor'),
    ),
  );
}

/**
 * Callback to upload images
 */
function redactor_wysiwyg_imageupload() {
  if (getimagesize($_FILES['file']['tmp_name'])) {
   $file = file_unmanaged_copy($_FILES['file']['tmp_name'], 'public://' . $_FILES['file']['name']);
   $file = file_create_url($file);

   drupal_json_output(array(
     'filelink' => $file
   ));

  } else {
    print t('Not a valid image');
  }
}

/**
 * Callback to upload files
 */
function redactor_wysiwyg_fileupload() {
  $file = file_unmanaged_copy($_FILES['file']['tmp_name'], 'public://' . $_FILES['file']['name']);
  $file = file_create_url($file);

  drupal_json_output(array(
    'filename' => $_FILES['file']['name'],
    'filelink' => $file
  ));
}

/**
 * Callback to link file upload
 */
function redactor_wysiwyg_linkfileupload() {
  $file = file_unmanaged_copy($_FILES['file']['tmp_name'], 'public://' . $_FILES['file']['name']);
  $file = file_create_url($file);

  print $file;
}

function redactor_wysiwyg_wysiwyg_include_directory($type) {
  return $type;
}

