<?php

/**
 * @file
 * Integrates redactor editors with Drupal.
 */

/**
 * Implements hook_wysiwyg_include_directory().
 */
function redactor_wysiwyg_include_directory($type) {
  return $type;
}

/**
 * Implements hook_redactor_plugins.
 */
function redactor_redactor_plugins($editor) {

  return array(
    'counter' => array(
      'name' => 'Counter',
      'files' => array(
        'js' => array(
          $editor['library path'] . '/plugins/counter.js',
        ),
      ),
    ),
    'clips' => array(
      'name' => 'Clips',
      'files' => array(
        'js' => array(
          $editor['library path'] . '/plugins/clips/clips.js',
        ),
        'css' => array(
          $editor['library path'] . '/plugins/clips/clips.css',
        ),
      ),
    ),
    'definedlinks' => array(
      'name' => 'Defined links',
      'files' => array(
        'js' => array(
          $editor['library path'] . '/plugins/definedlinks.js',
        ),
      ),
    ),
    'fontcolor' => array(
      'name' => 'Font color',
      'files' => array(
        'js' => array(
          $editor['library path'] . '/plugins/fontcolor.js',
        ),
      ),
    ),
    'fontfamily' => array(
      'name' => 'Font family',
      'files' => array(
        'js' => array(
          $editor['library path'] . '/plugins/fontfamily.js',
        ),
      ),
    ),
    'fontsize' => array(
      'name' => 'Font size',
      'files' => array(
        'js' => array(
          $editor['library path'] . '/plugins/fontsize.js',
        ),
      ),
    ),
    'fullscreen' => array(
      'name' => 'Fullscreen',
      'files' => array(
        'js' => array(
          $editor['library path'] . '/plugins/fullscreen.js',
        ),
      ),
    ),
    'limiter' => array(
      'name' => 'Limiter',
      'files' => array(
        'js' => array(
          $editor['library path'] . '/plugins/limiter.js',
        ),
      ),
    ),
    'table' => array(
      'name' => 'Table',
      'files' => array(
        'js' => array(
          $editor['library path'] . '/plugins/table.js',
        ),
      ),
    ),
    'textdirection' => array(
      'name' => 'Text direction',
      'files' => array(
        'js' => array(
          $editor['library path'] . '/plugins/textdirection.js',
        ),
      ),
    ),
    'textexpander' => array(
      'name' => 'Text expander',
      'files' => array(
        'js' => array(
          $editor['library path'] . '/plugins/textexpander.js',
        ),
      ),
    ),
    'video' => array(
      'name' => 'Video',
      'files' => array(
        'js' => array(
          $editor['library path'] . '/plugins/video.js',
        ),
      ),
    ),
  );
}

/**
 * get redactor plugin definition
 *
 * @return array plugin definition
 */
function redactor_get_plugin_definition($plugin_name) {
  $plugins = redactor_get_plugin_definitions();
  $plugin = isset($plugins[$plugin_name]) ? $plugins[$plugin_name] : null;

  return $plugin;
}

/**
 * Return redactor plugins definitions
 * @return array plugin definitions
 */
function redactor_get_plugin_definitions() {
  $plugins = &drupal_static(__FUNCTION__);

  if (!isset($plugins)) {
    $editor = wysiwyg_get_editor('redactor');
    $plugins = module_invoke_all('redactor_plugins', $editor);
  }

  return $plugins;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function redactor_form_wysiwyg_profile_form_alter(&$form, &$form_state, $profile) {
  if($form_state['wysiwyg']['editor'] == 'redactor') {
    return;
  }

  $form['plugins'] = array(
    '#weight' => -10,
    '#type' => 'fieldset',
    '#title' => t('Redactor plugins'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#tree' => TRUE,
    '#theme' => 'wysiwyg_admin_button_table',
  );

  $plugins = redactor_get_plugin_definitions();
  $profile = $form_state['wysiwyg_profile'];

  foreach($plugins as $name => $infos) {
    $form['plugins'][$name][$name] = array(
      '#type' => 'checkbox',
      '#title' => $infos['name'],
      '#default_value' => !empty($profile->settings['plugins'][$name][$name]) ? $profile->settings['plugins'][$name][$name] : FALSE,
      '#description' => NULL,
    );
  }

  array_unshift($form['#submit'], 'redactor_profile_form_submit');

  return $form;
}

/**
 * extra submit form callback
 *
 * @param object $form
 * @param object $form_state
 */
function redactor_profile_form_submit($form, &$form_state) {
  $values = &$form_state['values'];
  if (isset($values['plugins'])) {
    // Store only enabled plugins for each plugin.
    foreach ($values['plugins'] as $plugin => $plugins) {
      $values['plugins'][$plugin] = array_filter($values['plugins'][$plugin]);
    }
    // Store only enabled plugins.
    $values['plugins'] = array_filter($values['plugins']);
  }
}

/**
 * Get plugin config from hook_redactor plugin 'config' key
 * and merge it with wysiwyg_profile config values (admin form)
 *
 * @param string $plugin_name
 * @param object $wysiwyg_profile
 * @return array merged config
 */
function redactor_get_plugin_config($plugin_name, $wysiwyg_profile = null) {
  $config = array();

  $plugin = redactor_get_plugin_definition($plugin_name);

  if(!is_null($wysiwyg_profile) && isset($wysiwyg_profile->settings[$plugin_name])) {
    $config = $wysiwyg_profile->settings[$plugin_name];
  }

  if(isset($plugin['config'])) {
    $config += $plugin['config'];
  }

  return $config;
}



